// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAuth = "user_auth"

// UserAuth 用户鉴权表
type UserAuth struct {
	ID         int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`                // 序号
	GmtCreated time.Time `gorm:"column:gmt_created;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"gmt_created"`  // 创建时间
	GmtUpdated time.Time `gorm:"column:gmt_updated;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"gmt_updated"`  // 更新时间
	IsDelete   bool      `gorm:"column:is_delete;type:tinyint(1) unsigned;not null;comment:是否删除，0-未删除，1-删除，默认为0" json:"is_delete"`     // 是否删除，0-未删除，1-删除，默认为0
	Username   string    `gorm:"column:username;type:varchar(20);not null;uniqueIndex:username,priority:1;comment:账号" json:"username"` // 账号
	Password   string    `gorm:"column:password;type:varchar(256);not null;comment:密码，加密后" json:"password"`                            // 密码，加密后
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
