// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRecord = "record"

// Record 奖项信息表
type Record struct {
	ID            int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`             // 序号
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	CompetitionID int64          `gorm:"column:competition_id;type:bigint(20) unsigned;not null;comment:竞赛id" json:"competition_id"`        // 竞赛id
	Type          string         `gorm:"column:type;type:varchar(512);not null;comment:奖项类型" json:"type"`                                   // 奖项类型
	Remark        string         `gorm:"column:remark;type:varchar(512);not null;comment:备注" json:"remark"`                                 // 备注
}

// TableName Record's table name
func (*Record) TableName() string {
	return TableNameRecord
}
