// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "role"

// Role 角色表
type Role struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`             // 序号
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	Code      string         `gorm:"column:Code;type:varchar(255);not null;uniqueIndex:Code,priority:1;comment:角色编码" json:"Code"`       // 角色编码
	Name      string         `gorm:"column:Name;type:varchar(255);not null;uniqueIndex:Name,priority:1;comment:角色名" json:"Name"`        // 角色名
	IsEnable  bool           `gorm:"column:IsEnable;type:tinyint(1);not null;comment:启用状态:0-禁用;1-启用" json:"IsEnable"`                   // 启用状态:0-禁用;1-启用
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
