// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDict = "sys_dict"

// SysDict 系统字典表
type SysDict struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`             // 序号
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	Label     string         `gorm:"column:label;type:varchar(512);not null;comment:标签" json:"label"`                                   // 标签
	Value     string         `gorm:"column:value;type:varchar(512);not null;comment:值" json:"value"`                                    // 值
	Type      string         `gorm:"column:type;type:varchar(512);not null;comment:类型" json:"type"`                                     // 类型
	Remark    string         `gorm:"column:remark;type:varchar(512);not null;comment:备注" json:"remark"`                                 // 备注
}

// TableName SysDict's table name
func (*SysDict) TableName() string {
	return TableNameSysDict
}
