// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTeam = "team"

// Team 队伍信息表
type Team struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`             // 序号
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	LeaderID  int64          `gorm:"column:leader_id;type:bigint(20) unsigned;not null;comment:队长id；user_info.id" json:"leader_id"`     // 队长id；user_info.id
	Name      string         `gorm:"column:name;type:varchar(512);not null;comment:队伍名称" json:"name"`                                   // 队伍名称
	Remark    string         `gorm:"column:remark;type:varchar(512);not null;comment:备注" json:"remark"`                                 // 备注
}

// TableName Team's table name
func (*Team) TableName() string {
	return TableNameTeam
}
