// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserRoleRel = "user_role_rel"

// UserRoleRel 用户-角色表
type UserRoleRel struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`             // 序号
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	UserID    int64          `gorm:"column:user_id;type:bigint(20) unsigned;not null;comment:用户id" json:"user_id"`                      // 用户id
	RoleID    int64          `gorm:"column:role_id;type:bigint(20) unsigned;not null;comment:角色id" json:"role_id"`                      // 角色id
}

// TableName UserRoleRel's table name
func (*UserRoleRel) TableName() string {
	return TableNameUserRoleRel
}
