// Code generated by goctl. DO NOT EDIT.
package types

type AuthLoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captcha_id"`
}

type AuthLoginResp struct {
	Token string `json:"token"`
}

type GetAuthCaptchaResp struct {
	CaptchaId string `json:"captcha_id"`
	B64s      string `json:"b64s"`
}

type AuthLogoutReq struct {
	Token string `json:"token"`
}

type AddUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AddUserResp struct {
	ID int64 `json:"id"`
}
